package:
    type:           library
    name:           omnipay-robokassa
    title:          RoboKassa driver for Omnipay PHP payment library
    license:        MIT
    headline:       "Omnipay: RoboKassa"
    keywords:       php, omnipay, robokassa, merchant, payment
    namespace:      Omnipay\RoboKassa
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.

        This package implements [RoboKassa](http://robokassa.ru/) support for Omnipay.

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
